ARDUINO_DIR   = /usr/share/arduino
BOARD_TAG = uno
ARDUINO_PORT = /dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_55332333230351014090-if00

ARDUINO_LIBS = Wire
USR_LIB_PATH = ~/sketchbook/libraries
CFLAGS_STD = -std=c++11
CXXFLAGS_STD = -std=c++11

include /usr/share/arduino/Arduino.mk
include /usr/share/arduino/Common.mk

