#!/bin/bash

TARGET=$1
TASK=$2


ALL_mask=$(echo $TARGET|sed -e 's/[aA][lL][lL]//g')

if [ -z $ALL_mask ] && [ ! -z $TARGET ]; then
	ALL=1
fi

echo "****************************************************************"
echo "****************************************************************"

if [ ! -z $ALL ]; then
	TARGETS=( $(ls -d */) )
	for TARGET in "${TARGETS[@]}"; do
		echo ""
		echo "#############################"
		echo "# Working in $TARGET"
		echo "#############################"
		if [ ! -f "$TARGET"Makefile ]; then
			echo "$TARGET" doesnt have a Makefile!!!!
			echo I want a damn Makefile, NOW!!!
		else
			cd $TARGET
			ls -a
			make $TASK
			if [ "$TASK" == "upload" ]; then
				DEVICE=$(cat ./Makefile|grep "ARDUINO_PORT=\|ARDUINO_PORT = "|sed -e 's/=/ /g'|awk '{print $2}')
				if [ -f $DEVICE ]; then
					echo Pulling Serial port settings from:
					echo "        $DEVICE"
					stty -a < $DEVICE
				else
					echo I dont think $DEVICE
					echo "    is plugged in!"
				fi
			fi

			cd ..
		fi
		echo "Done with $TARGET"
		echo "#############################"
		echo ""
	done

elif [ ! -z $TARGET ]; then
	echo ""
	echo "#############################"
	echo "# Working in $TARGET"
	echo "#############################"
	if [ ! -f "$TARGET"/Makefile ]; then
		echo "$TARGET" doesnt have a Makefile!!!!
		echo I want one, immediately!!!
	else
		cd $TARGET
		make $TASK

		if [ "$TASK" == "upload" ]; then
			DEVICE=$(cat ./Makefile|grep "ARDUINO_PORT = \|ARDUINO_PORT="|sed -e 's/=/ /g'|awk '{print $2}')
			if [ -f $DEVICE ]; then
				echo Pulling Serial port settings from:
				echo "        $DEVICE"
				stty -a < $DEVICE
			else
				echo I dont think $DEVICE 
				echo "    is plugged in!"
			fi
		fi

		cd ..
	fi
	echo "Done with $TARGET"
	echo "###############################"
	echo ""
fi

echo "****************************************************************"
echo "****************************************************************"
