#!/bin/bash

TARGET=$1
TASK=$2


ALL_mask=$(echo $TARGET|sed -e 's/[aA][lL][lL]//g')

if [ -z $ALL_mask ] && [ ! -z $TARGET ]; then
	ALL=1
fi

if [ ! -z $ALL ]; then
	TARGETS=( $(ls -d */) )
	for TARGET in "${TARGETS[@]}"; do
		echo "#############################"
		echo "# Working in $TARGET"
		echo "#############################"
		if [ ! -f "$TARGET"Makefile ]; then
			echo "$TARGET" doesnt have a Makefile!!!!
			echo I want a damn Makefile, NOW!!!
		else
			cd $TARGET
			ls -a
			make $TASK
			DEVICE=$(cat ./Makefile|grep "port=\|port ="|sed -e 's/=/ /g'|awk '{print $2}')
			echo Pulling Serial port settings from:
			echo "\t"$DEVICE
			stty -a < $DEVICE
			cd ..
		fi
		echo "Done with $TARGET"
		echo "#############################"
	done

elif [ ! -z $TARGET ]; then
	echo TARGET: $TARGET
	if [ ! -f "$TARGET"/Makefile ]; then
		echo "$TARGET" doesnt have a Makefile!!!!
		echo I want one, immediately!!!
	else
		cd $TARGET
		make $TASK
		DEVICE=$(cat ./Makefile|grep "port=\|port ="|sed -e 's/=/ /g'|awk '{print $2}')
		echo Pulling Serial port settings from:
		echo "\t"$DEVICE
		stty -a < $DEVICE
		cd ..
	fi
fi
